#pragma once

#define RECOMMAND_BIT_RATE 5500000
#define DEFALUT_WIDTH 1920
#define DEFALUT_HEIGHT 1080

#define DEFALUT_FRAME_RATE 60

#define FRAME_TIME_OUT 0.02 

#define SEC_PER_CAP_FRAME 10 

#define SEC_PER_PRC_FRAME 3 

#define TIME_STEP_DIVISION 5 

#define BYTE_PER_PIXEL 4

#define AUDIO_SAMPLE_RATE 44100

#define DEFALUT_SEGMENT_SEC 1
#define DEFALUT_TIME_BASE_UNIT 1000
#define DEFALUT_PIX_FMT AV_PIX_FMT_YUV420P
#define GOP_SIZE 30

#define DEFALUT_MULTI_MEDIA_CODEC AV_CODEC_ID_MPEG4

#define DEFALUT_SAMPLE_RATE 48000
#define DEFALUT_AUDIO_CHANNEL 2